# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 茂同学的个人博客
email: mao@malatoday.com
description: > # this means to ignore newlines until "baseurl:"
  PHP党一枚。热爱编程，热爱生活，对新鲜的事物抱有极大的兴趣。对PHP，JS有一丝丝的见解。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://malatoday.com" # the base hostname & protocol for your site
github_username:  swumao
weibo_username: 西南喵喵
weibo_userid: 3913151499
background-color: #EEEEEE
# Build settings
markdown: kramdown
